static const FFCodec * const codec_list[] = {
    &ff_amv_decoder,
    &ff_flv_decoder,
    &ff_h263_decoder,
    &ff_h264_decoder,
    &ff_hevc_decoder,
    &ff_mjpeg_decoder,
    &ff_mpeg1video_decoder,
    &ff_mpeg2video_decoder,
    &ff_mpeg4_decoder,
    &ff_mpegvideo_decoder,
    &ff_msmpeg4v1_decoder,
    &ff_msmpeg4v2_decoder,
    &ff_msmpeg4v3_decoder,
    &ff_sp5x_decoder,
    &ff_vc1_decoder,
    &ff_vp8_decoder,
    &ff_vp9_decoder,
    &ff_webp_decoder,
    &ff_wmv1_decoder,
    &ff_wmv2_decoder,
    &ff_wmv3_decoder,
    &ff_av1_decoder,
    NULL };
